name: Actualizar marcadores

on:
  workflow_dispatch:       # Permite ejecutarlo manualmente desde GitHub
  schedule:
    - cron: '*/5 * * * *'  # Ejecuta cada 5 minutos

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar scraper
        run: python scraper.py

      - name: Subir cambios a GitHub
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add marcadores.json
          git commit -m "🔁 Actualización automática de marcadores" || echo "Sin cambios"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
